# Run as
# docker-compose build; docker-compose up -d

services:

  postgres_db:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_1
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    build:
      context: flask
      target: builder
    image: flask_migrate_backend
    stop_signal: SIGINT
    ports:
      - 5000:5000
    environment:
      FLASK_SERVER_PORT: 5000
      DB_URI: postgresql://postgres:postgres@postgres_db/db_1
    volumes:
      - ./flask:/src
      # expected directory structure: flask/app/app.py
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: true

  frontend:
    build:
      context: flutter
    image: flutter_frontend
    volumes:
      - ./flutter:/src
    ports:
      - 80:80
    environment:
      BACKEND_URI: http://backend
